### ISSUE TITLE
reduce_memory_usage to have an option to be silent , verbose=0, so it doesn't print info when executed

### ISSUE THREAD

**Issue by nemar3** [samarth-agrawal-86/fast_ml#15]
hi

thanks for writing this great package! 
small change request: I am using the reduce_memory_usage method in a script with many files, it issues some prints with information,which in my case has no practical usage.

A suggestion would be to have a verbose parameter

**Comment by samarth-agrawal-86** [comment]
added verbose = True/False parameter
